### PR TITLE
feature(core): use HardSource build caching

### PR DESCRIPTION
**Pull request by justingreenberg**
@yagudaev @davezuko ok, so i thought this would improve incremental builds but it doesn't... buttt it does use some clever dependency caching improve build BOOT times significantly ... could be useful for CI if you host your own environment

some benchmark...

```
npm run dev
```

sigterm and run again :)

**before:**
1. First Build Boot Time: 4512ms 
2. Second Build Boot Time: 2418ms

**after:**
1. First Build Boot Time: 6987ms 
2. Second Build Boot Time: 1495ms

other options include possibly using `happypack`,  which provides multiple threads, or just but the bullet and implement DLLs after all. i've really been reluctant, since it adds a lot of complexity and manual build steps to work properly. this means a lot of support... based on `HardSource`, i'm thinking there is probably a way to use similar dependency caching to trigger DLL builds... will think more about that

@yagudaev can you test this with your build and let me know results? not too many changes

### CODE REVIEW

**Comment by bytewiz** [comment]
@justingreenberg just tried it out:
What I did: 
 - I applied the changes from the files you changed
 - I did an initial build with and without the changes
 - I changed a `console.log` in one file and removed again for both scenarios, but got this:

*using your changes*
- init build : ~42s
- incremental: ~4s

*prev. setup*
 - init build : ~33s
 - incremental: ~4s

unfortunately didn't seem to help me much 😢

**Comment by davezuko** [comment]
Ahhhhhhhhh I was wondering why I wasn't able to find this PR despite knowing it existed, it's not to the main project repo. Will take a look at bringing this changes over. Thanks for commenting on it @bytewiz.

**Comment by bytewiz** [comment]
For the record I will try happypack, yp see if that resolves my problem

Den 3. okt. 2016 7.35 PM skrev "David Zukowski" <notifications@github.com>:

**Comment by justingreenberg** [comment]
@bytewiz i actually have a branch with that as well :)

https://github.com/justingreenberg/react-redux-starter-kit/tree/feature/parallellize-compile

this is from an older version of kit but relevant configs should all work

here's the diff:

https://github.com/davezuko/react-redux-starter-kit/compare/master...justingreenberg:feature/parallellize-compile?expand=1

**Comment by bytewiz** [comment]
Awesome, I will try it out then! Thanks

Den 3. okt. 2016 8.24 PM skrev "Justin Greenberg" <notifications@github.com

**Pull request closed without merging**
